#!/bin/bash

case $# in
0)	set `date`; m="no-month"; y=$6;;
1)	y=$1; set `date`; m="";;
2)	m=$1; y=$2;;
esac

case $m in
no-month)	m="";;
jan*|Jan*)	m=1;;
feb*|Feb*)	m=2;;
mar*|Mar*)	m=3;;
apr*|Apr*)	m=4;;
may|May)	m=5;;
jun*|Jun*)	m=6;;
jul*|Jul*)	m=7;;
aug*|Aug*)	m=8;;
sep*|Sep*)	m=9;;
oct*|Oct*)	m=10;;
nov*|Nov*)	m=11;;
dec*|Dec*)	m=12;;
*)		;;
esac

/usr/bin/cal $m $y
